kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
  - name: test-pod-ro
    image: gcr.io/google_containers/busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "echo Hello > /mnt/Hi || exit 1; while :; do sleep 10; done;"
    volumeMounts:
      - name: pvc
        mountPath: "/mnt"
        readOnly: false
  restartPolicy: "Never"
  nodeSelector:
    os: parallels # make sure you label your nodes to be ploop compatible 
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: vz-test-claim
