kind: Pod
apiVersion: v1
metadata:
  name: test-pod-ro1
spec:
  containers:
  - name: test-pod-ro
    image: gcr.io/google_containers/busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "while :; do sleep 10; done; while :; do let i=i+1; sleep 1; echo ok $i >> /mnt/date || break; done"
    volumeMounts:
      - name: pvc
        mountPath: "/mnt"
        readOnly: true
  restartPolicy: "Never"
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: vz-claim
