kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: run-vz-provisioner
subjects:
  - kind: ServiceAccount
    name: vz-provisioner
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: vz-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
